# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellroute < Formula
  desc "Run terminal commands through a proxy."
  homepage "https://shellroute.com"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.6/shellroute_0.1.6_darwin_amd64_brew.tar.gz"
      sha256 "9ba9d1f60f3d2c8bcb333b0b9d5d36990196db0a2b9f393a71f05ba896432afa"

      define_method(:install) do
        bin.install "shellroute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.6/shellroute_0.1.6_darwin_arm64_brew.tar.gz"
      sha256 "893f4a45a91e3c6bfba8456a43fb510c3a57ab726e0e36bf0dc727347fcf38c1"

      define_method(:install) do
        bin.install "shellroute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.6/shellroute_0.1.6_linux_amd64_brew.tar.gz"
      sha256 "6074150ffe8d3bfba4a1fdc2d1770bd5bcb4e20b755b77eb46f7415a62293d6f"
      define_method(:install) do
        bin.install "shellroute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.6/shellroute_0.1.6_linux_arm64_brew.tar.gz"
      sha256 "751feb705ba8a98ca54d7edbc1df94dfbeb1d70acb2153b9a98c42a55b82f027"
      define_method(:install) do
        bin.install "shellroute"
      end
    end
  end
end
