# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellroute < Formula
  desc "Residential proxy CLI"
  homepage "https://shellroute.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.0/shellroute_0.1.0_darwin_amd64_brew.tar.gz"
      sha256 "826652e6414e6ebb604690686fa4e02e92ec1dbdfb67f18c758f0c2d10180bb7"

      define_method(:install) do
        bin.install "shellroute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.0/shellroute_0.1.0_darwin_arm64_brew.tar.gz"
      sha256 "928b6cdad4c8c1e35207f75e2609309e9ec452e83b848eaa5c281257ad62d7e4"

      define_method(:install) do
        bin.install "shellroute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.0/shellroute_0.1.0_linux_amd64_brew.tar.gz"
      sha256 "6e870f45d0cc6be175fee3a89677d6c1c587fac18f9d21d2ab0b5f229a588810"
      define_method(:install) do
        bin.install "shellroute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shellroute/shellroute-cli/releases/download/v0.1.0/shellroute_0.1.0_linux_arm64_brew.tar.gz"
      sha256 "044a225118d315d0df01195248dcdd76bb77f4f2b42e0c783510c56c63096a0e"
      define_method(:install) do
        bin.install "shellroute"
      end
    end
  end
end
